[buildPlans.iosevka-curly]
family = "Iosevka Curly"
spacing = "term"
serifs = "sans"
no-cv-ss = true
export-glyph-names = true

  [buildPlans.iosevka-curly.variants]
  inherits = "ss20"

[buildPlans.iosevka-curly.widths.normal]
shape = 600
menu = 5
css = "normal"
