require("user.options")
require("user.plugins")
require("user.colorscheme")
require("user.neoscroll")
require("user.nvim-tree")
require("user.treesitter")
-- require("user.nvim-cmp")
-- require("user.lspconfig")
require("user.bufferline")
require("user.keymaps")
require("user.toggleterm")
require("user.indent-blankline")
require("user.copilot")

